### ISSUE TITLE
Make --prof toggleable

### ISSUE THREAD

**Issue by davidmarkclements** [nodejs/diagnostics#154]
As #150 – however since perf support in V8 is supposedly deprecated (as mentioned in #148) this could be the more important flag moving forward

**Comment by davidmarkclements** [comment]
(also because interpreted frames – https://github.com/nodejs/diagnostics/issues/150#issuecomment-365330166)

**Comment by ryzokuken** [comment]
@hashseed would you be open to a PR making `--prof` toggleable? Would love to give this one a shot.

**Comment by ryzokuken** [comment]
@hashseed ping.

**Comment by davidmarkclements** [comment]
Hey @ryzokuken - Just to say I discussed this with @hashseed in person - it's really non-trivial (aside from other the internal implementation complexities think about the log format - if it's toggglable when do you get the code creation events? Those have to be collected and stored right? So even if it's off there's an increased cost, and likely more memory consumption) 

Even given a viable approach that doesn't have unreasonable cost, --prof is internal/private to V8 so we can't currently expect the V8 team to have the same resources to invest in this than public apis

**Comment by mmarchini** [comment]
Just want to point out that it's possible to implement this feature with no memory overhead if you iterate the heap and get all codes generated when you start the profiler (which is already done when we use --prof to collect codes loaded from V8's snapshot). The only overhead will be for users of the toggling feature, which is acceptable. If I'm not mistaken, @mcollina was also asking for this feature.

**Comment by ofrobots** [comment]
FYI @hashseed is presently on vacation. He may not be able to respond to this thread until he's back.

**Comment by slonka** [comment]
Any updates on this?

**Comment by kwasimensah** [comment]
ping. Just ran into this. I'm trying to profile code but don't want my setup code in the profile

**Comment by mmarchini** [comment]
`--prof` is a V8 flag, so for those interested in this feature the best place to request it is in the V8 issue tracker: https://bugs.chromium.org/p/v8/issues/list.

---

@kwasimensah thera are a few alternatives to `--prof` if you need to profile your code on demand (without startup):

1. You can use the Inspector Protocol to trigger V8 CPU Profile and open the output on Chrome DevTools. This can be achieved either with the [Inspector API](https://nodejs.org/api/inspector.html#inspector_cpu_profiler), npm modules like [thetool](https://www.npmjs.com/package/thetool#on-demand-tooling), or completely on-demand connecting to the Inspector Protocol websocket and exchanging messages (I'm not aware of any guides for this last one though)
2. You can use the C++ API to trigger a V8 CPU Profile. This is essentially the same as `1`, but it uses the [C++ API](https://github.com/nodejs/node/blob/578e4eddb97fffd6b9f1fe527da865875efa73f1/deps/v8/include/v8-profiler.h#L301) instead of the Inspector Protocol. There's probably an npm module with bindings for this
3. If you are on Linux, you can use Linux `perf` in combination with `--interpreted-frames-native-stack` and `--perf-basic-prof` flags, as described here: https://nodejs.org/en/docs/guides/diagnostics-flamegraph/
