### ISSUE TITLE
Proposal for Promise hooks to improve performance.

### ISSUE THREAD

**Issue by hashseed** [nodejs/diagnostics#188]
@bmeurer, @ofrobots and I discussed and [put some thoughts together](https://docs.google.com/document/d/1y4lF-iQhhuSOgzlPIBbfCT4IUpg-in3az5Q87C7aY3Q/edit). Comments welcome!

**Comment by hashseed** [comment]
Ah yeah. Totally forgot. Thanks.

**Comment by hashseed** [comment]
As discussed during the WG meeting, @mcollina is going to reach out to find out why async hooks were designed around async IDs and whether adding the resource would be ok.

**Comment by Qard** [comment]
Definitely a 👍 from me. There's no reason for all this work to be done on the native side. No one uses it there.

One thing I'd like to bring up, which I think is relevant, and I have commented on several times in the past is that async_hooks and the previous iteration in AsyncListener both made the mistake of conflating resource lifecycle with asynchronous boundary linkage. I think that has long been a major failing, preventing the feature from working optimally.

Some want to track the resource lifecycle, which makes sense for exhaustible resources like sockets and file descriptors. However, that really doesn't make sense for something like promise hooks. Promises are not an exhaustible resource, the object itself is not actually relevant. For asynchronous continuity, it's actually the _callback_ that we care about--namely, linking where it was declared to where it was executed.

I feel like it would have made a lot more sense to have one system which tracks creation and destruction of _true_ resource handles, and then a completely separate feature used exclusively for connecting async task init points to the callback start and end. Resources would generally need native code to track those lifecycle points, but the barrier tracking can be implemented 100% in JS. (I actually wrote exactly this as an experiment several years ago. https://github.com/qard/stacks-concept)

**Comment by AndreasMadsen** [comment]
**I'm -1**. Maybe this is the correct approach, but it completly skips over the memory issues that have been reported. I think the memory issue is actually what we have gotten most uninfluced feedback about (feedback where we didn't ask directly, "what is the performance overhead").

In fact two companies have reached out to me personally about memory issues, non about computationally issues. There are also some issues:

* https://github.com/nodejs/node/issues/14446
* https://github.com/Jeff-Lewis/cls-hooked/issues/11

I remember there being more, but perhaps they are not in nodejs/node.

> As discussed during the WG meeting, @mcollina is going to reach out to find out why async hooks were designed around async IDs and whether adding the resource would be ok.

Two reasons:

**Reason 1:**

The destoy hook was added because the rest isn't always enogth information. It would allow you to:
* Find unresolved promises
* Know when a resource will no longer emit (setInterval, http.createServer)
* Track active handles

If you want to get meta information from the `init` hook (such as the stack-trace) in the `destroy` hook, then you can't use a WeekMap. Because when the `destroy` hook is emitted, the `resource` object is GC'ed and thus you have lost your WeekMap key. That is why we use the `asyncId`.

**Reason 2:**

WeekMap have a very bad memory profile. 

In https://github.com/AndreasMadsen/trace/issues/17 someone reported that `trace` used an extream amout of memory on something as simple as:

```js
require('trace')
var stream = require('fs').createReadStream('huge file here')
stream.resume()
```

Turns out that WeakMap are really bad for memory consumtion, especially in cases where you get a very determinstic `destroy` hook, such as the `nextTick` case.

 >**WeakMap using handle object**
> ![4-weak-map](https://cloud.githubusercontent.com/assets/505333/12008115/f365ef98-ac26-11e5-839f-a5f43c908626.png)

> **Map using uid and destructor event**
> ![5-fix](https://cloud.githubusercontent.com/assets/505333/12008117/f9b227a4-ac26-11e5-863f-6e67716cae97.png)

Removing the destroy hook and using WeakMaps means that we can't efficiently cleanup after `nextTick`, an async resource that is much more common than promises.

I also understand that to more efficiently garbage collect promises in the future, using ecape-analysis, we can't depend on the `promise` object in the `init` hook. Something that this proposal makes us very depedent on. And inefficient garbage collection for promises is still going to be an issue with WeakMaps, as the value can't be GC'ed before the key is GC'ed and for that we would need ecape-analysis.

**Comment by AndreasMadsen** [comment]
> * Escape analysis is already not possible due to exposing the promise to the init hook.

We don't need to expose the `promise` object in the init hook. The only use case is to call `promise.then()` and the https://github.com/angular/zone.js team would actually prefer to get the value in `resolve(value)` through the `promiseResolve` hook.

> * We also cannot perform escape analysis with the current PromiseHook API that goes through C++, since we cannot inline across calls into C++.

We only use the promise object for assigning `asyncId` and emitting the destroy hook. If V8 provided an API for that we wouldn't need the promise object in PromiseHook.

I have said this quite a few times, I think most details is in here: https://github.com/nodejs/benchmarking/issues/181#issuecomment-352281725 and comments futher down.

**Comment by mmarchini** [comment]
@Qard do you want to keep this issue opened?

**Comment by Qard** [comment]
Everything that can be done from Node.js perspective has already been done, so I think so, yes.

It _would_ still be nice to have V8 supply a version of the API which takes `v8::Function` though.

It may also be worth looking into skipping non-observable promises, though it seems like the V8 folks have actually just tried to _eliminate_ some of those altogether since the doc for that issue was originally written. Not sure how relevant that last idea is at this point.
