### ISSUE TITLE
Node.js  Diagnostics Deep Dive Meeting 2020-07-29

### ISSUE THREAD

**Issue by mhdawson** [nodejs/diagnostics#419]
## Time

**UTC Wed 29-Jul-2020 16:30 (04:30 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Wed 29-Jul-2020 09:30 (09:30 AM) |
| US / Mountain | Wed 29-Jul-2020 10:30 (10:30 AM) |
| US / Central  | Wed 29-Jul-2020 11:30 (11:30 AM) |
| US / Eastern  | Wed 29-Jul-2020 12:30 (12:30 PM) |
| London        | Wed 29-Jul-2020 17:30 (05:30 PM) |
| Amsterdam     | Wed 29-Jul-2020 18:30 (06:30 PM) |
| Moscow        | Wed 29-Jul-2020 19:30 (07:30 PM) |
| Chennai       | Wed 29-Jul-2020 22:00 (10:00 PM) |
| Hangzhou      | Thu 30-Jul-2020 00:30 (12:30 AM) |
| Tokyo         | Thu 30-Jul-2020 01:30 (01:30 AM) |
| Sydney        | Thu 30-Jul-2020 02:30 (02:30 AM) |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Diagnostics%20Deep%20Dive+Meeting+2020-07-29&iso=20200729T16
* or http://www.wolframalpha.com/input/?i=04PM+UTC%2C+Jul+29%2C+2020+in+local+time

## Links

* ~Minutes Google Doc: <https://docs.google.com/document/d/12BP5Y1Ivcrd3sJBOh7iRgDvTu6G8CmCdpG-FhVTi9x8/edit>~
* Minutes HackMD (we'll be using this one for the meeting): https://hackmd.io/s/BkHb6jnew

## Agenda

Extracted from **diag-deepdive-agenda** labelled issues and pull requests from the **nodejs org** prior to the meeting.

### nodejs/diagnostics

* Deep Dive Suggestion: triaging existing long-standing issues [#416](https://github.com/nodejs/diagnostics/issues/416)
* Deep Dive Suggestion: list subsystems which would benefit from trace points [#415](https://github.com/nodejs/diagnostics/issues/415)
* Discuss usage and support of eBPF [#386](https://github.com/nodejs/diagnostics/issues/386)
* Diagnostics Best Practices Guide content definition meeting [#254](https://github.com/nodejs/diagnostics/issues/254)

## Invited

* Diagnostics deep dive meetings: @nodejs/diagnostics

## Notes

The agenda comes from issues labelled with `diag-deepdive-agenda` across **all of the repositories in the nodejs org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

* link for participants: https://zoom.us/j/466707925
* For those who just want to watch: youtube admin page: https://www.youtube.com/my_live_events?filter=scheduled

**Comment by mmarchini** [comment]
FYI I changed the minutes link to a HackMD link for trial. We usually don't have much on the notes for deep dives anyway, so it shouldn't be disruptive.

**Comment by mmarchini** [comment]
For this week I suggest we continue the deep dive into "unexpected behavior" use journey. If folks think we should discuss something else let me know.

**Comment by mhdawson** [comment]
+1, I may be a bit late but will join as soon as I can after my previous meeting.

**Comment by RafaelGSS** [comment]
@mmarchini could elaborate about the "unexpected behavior"? If has any doc about it, just to understand more to the meeting.

**Comment by mmarchini** [comment]
Sure. We use Deep Dive meetings to discuss a single topic in depth, and for the past few months we've been using that time to discuss [User Journeys](https://github.com/nodejs/diagnostics/issues/295) with three goals: 1) listing existing tools and techniques to handle a given problem; 2) identifying gaps in tooling (problems that don't have appropriate tooling to be investigated and solved); and 3) write documentation on [diagnostics best practices](https://github.com/nodejs/diagnostics/issues/295) based on our findings. 

We've been tackling this by focusing on the symptoms user find instead of focusing on the tools. As an example, we didn't start discussing how to use Linux perf, instead we discussed which symptoms the user sees when experiencing a performance issue, and what steps they should take to determine if Linux perf or V8 CPU Profiler or something else is the best tool for investigation.

"Unexpected behavior" is essentially everything the application does that it shouldn't: return incorrect values in response to a request, or wrong status code or don't return nothing, for example. In the last meeting we discussed some of the possible symptoms and causes for unexpected behavior. You can see the evolving document [here](https://docs.google.com/document/d/1ivHjgzucnA6QVYyS535EHg-kYQhGJCm9v1Jn5ntSxT8/edit?usp=sharing). We already covered other topics if you want to take a look how the document looks after discussion: [Performance](https://docs.google.com/document/d/1Yip9zU_8axfZwN-clGMeoNWVYHZPfBjepLV3Ur2JjwA/edit?usp=sharing), [Memory](https://docs.google.com/document/d/16PeoMhREmJxSbrpyom9Uypl2lJuMsqAfB96oocDTPwQ/edit?usp=sharing) and [Crashes](https://docs.google.com/document/d/1gd_4hlDK-DacbyTnFcqLPdCjM1Q1z02MdkFaUddPLCE/edit?usp=sharing), Discission on each topic usually takes a few meetings.

Finally, based on those discussions we add/improve [documentation in the repository](https://github.com/nodejs/diagnostics/tree/master/documentation), which we intend to include in the [redesigned Node.js website](https://nodejs.dev/).

The recordings for the last deep dive are available [here](https://www.youtube.com/watch?v=HqhbnkoUxBM) if you want to take a look.

**Comment by RafaelGSS** [comment]
@mmarchini it's clear for me now! Thanks.
