### ISSUE TITLE
Do we know what performance impact v8 code coverage has? 

### ISSUE THREAD

**Issue by naugtur** [nodejs/diagnostics#487]
Context: I'm wondering if it'd be possible to run an app in production with coverage turned on all the time to collect all reachable lines in dependencies and use that information to later reason about known vulnerabilities - if they apply to the app or not.

Question: Would running with coverage always on for weeks make any sense?

**Comment by Flarna** [comment]
The overhead should be acceptable in recent node.js versions as most work is actually done outside of the JS thread.
There was an issue with higher overhead during starting a profiler session in some cases but it seems this has been fixed in v8 recently (see https://github.com/nodejs/diagnostics/issues/444#issuecomment-869241600).
