### ISSUE TITLE
Node.js Collaboration Summit diagnostics discussion minutes

### ISSUE THREAD

**Issue by watson** [nodejs/diagnostics#95]
These are my raw notes taken at the Node.js Collaboration Summit in Berlin. Sorry for the mess 😅. I'll update when new stuff comes up. Feel free to add stuff I missed 😃

## Day 1: 2017-05-04

**Problem:** How do we make it easier for APM vendors to instrument node-core and userland modules without having to monkey-patch everything (even after AsyncHooks lands)?

**Suggestion:** We need to make it easier for module owners to know how to structure and build their modules so they are easier to instrument. We can make a guide on https://nodejs.org/en/docs/guides/ that specifies how module owners should make their modules easy to instrument.

Topic ideas:

- How to use the AsyncHooks Embedder API
- How to send detailed tracing events to APM vendors using some API

Other notes:

- This should be a living document
- Discussion on this could be had on a PR that’s opened to the nodejs.org website creating this guide

**Problem:** Can we standardise the way tracing information is sent from an instrumented module (called module-x below) to an APM agent?

**Suggestions:**

- Maybe we can use the V8 trace events API
    - Pros: No need for module-x to know about the APM agents
    - Cons:
        - Currently no way to bind the trace event to the current context
        - Might be expensive to cross the barrier into C-land
        - Might not be detailed enough
        - Overhead of running in production?
- Alternatively invent a new API in JavaScript land
    - This could either be in Node core or a userland module
    - If it’s a userland module, then module-x needs to detect if it’s present before it can send events to it. The APM agents need to do the same.
        - What if there’s multiple versions of this module installed?
    - Research if other languages have something similar

**Comment by sam-github** [comment]
Hooks should simplify APM code, but there is no way to get context data (`fs.open()`'s `path`, HTTP path/method, etc.), so does not remove the need to monkey-patch the API surface for APM's that need such information (hooks alone are sufficient for CLS style code that only needs to track continuations).

The Embedder API now exists - it didn't at time of NINA Austin. It allows thirdparty modules to interact with the hooks to indicate "intent" and provides a uniform solution of the "connection pooling" aka "async queueing" problem (cf. https://docs.google.com/document/d/1tlQ0R6wQFGqCS5KeIw0ddoLbaSYx6aU7vyXOkv-wvlM/edit#). This is great, APMs look forward to this, it decreases the need for continuous adaption of our code bases to the changes in internals of thirdparty modules, because they can maintain their use of the Embedder API themselves.

APM builders present:
- danbev, dynatrace
- thomas watson, opbeat
- sam roberts, strong-agent, concurix, appmetrics
- jkrems, groupon (which has an internal "APMish" framework)

Promises are problems, interaction with utask queue is hard to track, and we need to patch v8 promises and the bluebird promises (at least)

Q: do/will hooks help with that?

Mongo has an APM API so monkey-patching is not necessary, and they maintain the API themselves. This is a great pattern, perhaps we should more clearly advocate it as something that npm packages that want to support APM reporting can do, perhaps we can even advocate a specific API/API pattern. cf. http://mongodb.github.io/node-mongodb-native/2.0/reference/management/apm/

elasticsearch may get an APM API soon (according to @watson)

Maybe we can get some common push behind an API for this, and put out a blog
with examples showing how to use the Embedder API and also solve the app-specific
info collection problem. The information on the app-specific could perhaps
be emitted as V8 trace events. We were all quite interested in publishing a guide that clearly reflects what APM vendors would like packages to do so that they would be easier to support reporting on by APM builders, and what the intended use of the Embedder API is.

We can could work on this by PRing a guide.

We should start talking about it in the diagnostics meetings.

V8: does it have js APIs? Does it have levels? Is the timing of it acceptable,
will it work us? Can trace events be used?
- https://github.com/nodejs/diagnostics/issues/82
- https://github.com/nodejs/diagnostics/issues/83
- https://github.com/nodejs/diagnostics/issues/84

async hooks:
- https://github.com/nodejs/node-eps/pull/18
- https://github.com/nodejs/node/pull/11883

**Comment by matthewloring** [comment]
I wish I could have attended this! Just to speak quickly to:

> Promises are problems, interaction with utask queue is hard to track, and we need to patch v8 promises > and the bluebird promises (at least)
> 
> Q: do/will hooks help with that?

I recently worked with the V8 team and @trevnorris to have Promise Hooks ([interface](https://github.com/nodejs/node/blob/master/deps/v8/include/v8.h#L5833), [design doc](https://docs.google.com/document/d/1rda3yKGHimKIhg5YeoAmCOtyURgsbTH_qaYR79FELlk/)) added to V8 so that async hooks can observe promise lifecycles. I have also prototyped an integration of these promise hooks into async hooks but we decided to wait to add this support until the existing async hooks PR lands as it is already quite complex. So, I guess the answer is hopefully async hooks should help once the initial implementation + promise hook integration follow-on have both landed.

**Comment by danielkhan** [comment]
It was daniel khan, dynatrace :)

I would prefer more of a standard over a blog. It can live under /guides on the Node.js website. I could think of a blog post that describes the problems APM vendors are facing today, though. This would give us something to pass on to customers to baseline their expectations when it comes to Node monitoring. I could sketch something out for you to review, ok?

**Comment by sam-github** [comment]
@danielkhan Sorry Daniel! Updated. I agree, a guide makes more sense (with a blog to point out its existence)

**Comment by mhdawson** [comment]
Guide + intro blog with pointer was what we settled on in the discussions.

**Comment by mike-kaufman** [comment]
Per discussion in Diag WG Meeting on 2017-12-13, we decided to open a seperate issue (#134) to track the latter issue here ("Can we standardise the way tracing information is sent from an instrumented module"), and we decided to close this one. 

Plz re-activate If something else in this thread is lost & needs tracked.
